# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# sites we inspire to be
# https://github.com/mmistakes/hpstr-jekyll-theme
# http://hyde.getpoole.com/

# Site settings
title: "Focus Beauty"
subtitle: "Professional Eyelash Extensions"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/focusbeauty" # the subpath of your site, e.g. /blog
url: "http://www.blairanderson.co/" # the base hostname & protocol for your site
google_analytics: 'UA-61052500-1'
twitter_username: focusbeauty
github_username:  focusbeauty

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

collections:
  landing:
    output: true
    permalink: /awesome/:path/
