# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# sites we inspire to be
# https://github.com/mmistakes/hpstr-jekyll-theme
# http://hyde.getpoole.com/

# Site settings
title: "Focus Beauty"
subtitle: "Professional Eyelash Extensions"
phone: '425.555.1212'
email: 'focusbeauty@gmail.com'
description: > #
  Professional eyelashes. Serving as far North East as Bothell, and South West
  as Vashon Island.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://focusbeauty.github.io/" # the base hostname & protocol for your site
google_analytics: 'UA-61052500-1'
twitter: focusbeauty
instagram: focusbeauty
facebook: focusbeauty
github:  focusbeauty

prose:
  siteurl: 'http://focusbeauty.github.io'

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

collections:
  landing:
    output: true
    permalink: /lashes/:path/
